# This Macro is to Generate Phonons Caustics patterns
/run/numberOfThreads 10
/run/initialize

/gps/energy 0.03 eV
/gps/number 1
#/gps/ang/type iso
#/gps/pos/centre 0.0 0.0 0 cm

# Point source
#/gps/pos/type Point
#/gps/pos/centre 0.0 0.0 0.262 mm
#/gps/ang/type iso
#/gps/ang/mintheta 0 deg
#/gps/ang/maxtheta 90 deg

# circular source
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0.0 0.0 -0.0495 mm
/gps/pos/radius 0.3 mm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg


/process/inactivate phononScattering
/process/inactivate phononDownconversion
/run/printProgress 10000
/run/beamOn 60000000
# /run/beamOn 100000000